setup.sh

Make the startup script less aggressive, so that it does not automatically
install or update python on your machine.
Ideally, we would also verify the python version, but this requires too much
string parsing to be worth the time at this point.

ABD-41: Don't automatically install or update python.

---

Dockerfile
build.jenkins
pre-commit.sh
run-tests.sh

We want to be able to run postgres locally in order to test that we can
correctly write to a Database. (Postgres is a good match for RDS running
Postgres)
Ideally, we would do this by spinning up a side-car docker container running
just postgres, and connect to that, but unfortunately side-car containers
are not secure in jenkins. We are therefore running postgres directly
within our python test-runner container.
Pre-commit now builds the container for us, and runs tests from within the
container, rather than running them directly on your local system.
Things that aren't yet ideal.
- it prints the output 'event-emitter-container' quite a lot
- it re-installs requirements.txt each time, which is a little slow.
Solo: @michaelwalker.

ABD-41: Tests now run in a docker container with postgres running.

---

build.jenkins

This should ensure that it has permission to run all steps.
Solo: @michaelwalker.

ABD-41: Allow Jenkins agene to run as 'privileged'.

---

pre-commit.sh

Previously the docker commands just printed 'event-recorder-container' to
the output quite a lot.
This has now been changed to make it more descriptive. eg
'Stopped container: event-recorded-container'

ABD-41: Improve output of pre-comit.

---

README.md
kill-docker.sh
pre-commit.sh
start-docker.sh

Previously these tests could only be run from within the docker container.
To make this possible, I have
- added `-p 5432:5432` to the docker build to expose the Postgres port to the host machine
- refactored pre-commit to have a 'start-docker' and 'stop-docker' scripts to make starting docker locally simple.
- added a section to the readme about this.

ABD-41: Enable devs to run postgres tests from their IDE.

---

.gitignore
setup.sh

The convention is to just call this directory env, so lets switch to
follow that convention.
Also fix a bug where we used the global pip to install deps, rather than
the one supplied by virtualenv.

BAU: Rename the virtualenv folder to env - and use it's pip.

---

src/decryption.py
src/kms.py
test/event_handler_test.py
test/test_encrypter.py

Update an event recorder system to decode base64 encrypted event encryption key before it attempts to decrypt the key.
Update the event recorder system to decode a whole base64 encrypted message before attempting to decrypt it using the event encryption key.
Authors: @adityapahuja

344: Fix decryption process issues

---

src/database.py
test/event_handler_test.py

Currently, a database is rejecting event messages since their timestamp's format is integer and the database expects it to be in date time format. This change updates an event recorder system to convert the event message's timestamp from integer into datetime so that the message can then be stored in the database without errors.
Authors: @adityapahuja

353: Store event's timestamp in datetime format

---

requirements/dev.txt
requirements/prod.txt
src/decryption.py
test/decryption_test.py
test/event_handler_test.py
test/test_encrypter.py

- This PR uses 2 commits to prove that the libraries are functionally the same (for our usage)
- The first only changes code in `src` and tests still pass
- Second does cleanup to remove dependency entirely

Trello-4pAQRrkO: Replace PyCrypto

---

src/database.py
src/event_handler.py
test/event_handler_test.py

- Added support to provide the encryption key in an encrypted env var instead
of from S3
- Added support for encrypting the database password instead of adding it in
plain text :scream: https://trello.com/c/CXREwQgE/157-encrypt-database-password-in-lambda

BAU: Shuffle some encryption

---

src/database.py
src/import_handler.py
test/import_handler_test.py

Changed write_audit_event_to_database method so that it returns true if insert into audit event table succeeds.
Changed import handler to skip billing and fraud event tables if write_audit_event_to_database returns false.
Co-authored-by: George Lund <george.lund@digital.cabinet-office.gov.uk>

qGlDDEZH/79: Inconsistent data in Billing and Fraud tables refactor

---

src/event_handler.py
test/event_handler_test.py

PR #34 introduced additional logging, however, it contain an error (https://github.com/alphagov/verify-event-recorder-service/pull/34)
Corrected order of execution so that `event` is evaluated before being used in an log statement.

BAU: Fix Logging Errors from PR #34

---

README.md
src/database.py
src/event_handler.py
src/import_handler.py
test/import_handler_test.py

IAM database authentication is now enabled on RDS and new user, `iam_writer`, has been created.
This change alters the recorder, and import service, to get an IAM authentication token if the
database password is not provided in the environment (in the `ENCRYPTED_DATABASE_PASSWORD` environment variable`).

HJ63P95U: Modify event recorder to use new IAM authentication to DB

---

database-schema/permissions/revoke_writer_permissions.sql

Record of `REVOKE` statements used to remove rights for old `writer` user.

 8WXtKLdP: Clean up old DB Writer users and passwords

---

database-schema/permissions/create_iam_reader_permissions.sql

The iam_reader user also needs to have `TEMPORARY` permission in order to create the temporary tables when running the rp_billing report.
This change is made manually on the db at the moment and reflects things that have already been applied.

Add Temporary permission for iam_reader user

---

pre-commit

In response to an incident, we're adding a check to our pre-commit scripts
to ensure no AWS credentials are being committed. It's using the AWS-provided
git secrets script - https://github.com/awslabs/git-secrets

Check for AWS credentials being committed

---

build/run-tests.sh
src/database.py
test/event_handler_test.py

The `billing_events` table current has no primary key defined. It has been determined that we should ideally use the event_id for this. Unfortunately, event_id is not currently stored in this table.
This card is to update the billing recorder service to populate the `event_id` column when creating new `billing_events`.
Storing the `event_id` will enable efficient joins to both the `audit_events` table and the new `billing_status` table.
Update tests to check for `event_id` value
Add `event_id` column to `INSERT` statement in `database.write_billing_event_to_database`
Also updated `run-test.sh` to tell Docker not use layer cache as it was using cached version of Postgres image rather than pulling latest migration scripts.

Wu7e9auF: Update Billing Recorder to populate event_id column on billing_events

---

build/package.sh

This is needed because the Docker image `dcind` to be used by a Concourse build task does not have Bash.
A similar change was made to `verify-event-system-alarm-notifier` repo in this [PR](https://github.com/alphagov/verify-event-system-alarm-notifier/pull/2).

Switch to using Bourne instead of Bash shell in `package.sh`

---

README.md

Now that the CI/CD pipeline is in place for the event recorder lambda, added a brief note in README so that this is obvious.

Update README to include brief info about automated release pipeline

---

.env
README.md
build/run-tests.sh
docker-compose.yml
postgres.Dockerfile
src/database.py
test.env
test/event_handler_test.py

The tests are broken for two reasons:
1) The log output is has changed since the introduction of the `event_id` column to the `billing_events` table.
2) The use of a "repeatable" migration in the database scripts repo has means the PostgreSQL initialise scripts run in the wrong order and the event-store service fails to start.
We need to ensure a sensible log output and set the expectations appropriately in the tests.
We should use Flyway to apply the migration scripts to local database instance to ensure consistent behaviour.
We can't run tests successfully == potential bugs
Fix logging and log expectation since introduction of unique `event_id` column to `billing_events` table.
Improve error handling in `build/run-tests.sh`.
Update `docker-compose.yml` to include Flyway task to run …

lf6wlZNL: Fix Tests and Database Migration Handling

---

src/database.py
test/event_handler_test.py

We often need to know which service to associate a billable event with. We do this by running the 'verifications by RP' report, which uses some data from the billing report but adds in a column containing the service name for each report.
We could just include that column in the billing report.
We could stop running the verifications by RP report. 
Secondary reports that use that report could be simplified.
Change `write_billing_event_to_database()` to also write `transaction_entity_id` from original event details.

Ndcbw4d3 add service name to billing report

---

src/database.py
test/event_handler_test.py
test/import_handler_test.py

As a developer, I want to be able to join between data in the `billing.fraud_events` table and the more detailed information in the `audit_events` table.
* For consistency with billing events, the primary key should be event ID
* Add the `transaction_entity_id` to fraud_events also
https://github.com/alphagov/verify-event-system-database-scripts/pull/41
Change `write_fraud_event_to_database()` to also insert `event_id` and `transaction_entity_id` from the original event.

LbFKGVYc: Fixes to database schema for existing fraud data - Recorder Changes

---

requirements/dev.txt
requirements/prod.txt
src/common.py
src/database.py
src/event_handler.py
src/idp_fraud_data_handler.py
src/idp_fraud_event.py
src/import_handler.py
src/s3.py
src/upload_session.py
test/event_handler_test.py
test/helpers.py
test/idp_fraud_data_handler_test.py

We now have an S3 bucket to which members of the fraud team can write files. We now need to process these files.
We will write a lamda that runs when file is uploaded to bucket (triggered by a Cloudwatch event).
We should validate the file and throw appropriate errors
In this card we should handle the success cases correctly, we will handle validation in and what to do with error cases in a different card.
Add `idp_fraud_data_handler` and test
Add logic to process incoming event and create an upload session record in database
Persist data in `idp_data.idp_fraud_events`
Persist contra indicators in  in `idp_data.idp_fraud_event_contraindicators`
Refactor tests to share 'helper' methods
Add matching of events to data in `billing.fraud_events`
Add basic error handling
Move upload file to …

YYdbmOjj: lambda to process the data thats uploaded and put it into the database

---

src/database.py
test/event_handler_test.py
test/helpers.py
test/import_handler_test.py

This PR is one part of several across Verify to be able to support billing for new special case `LOA2,LOA1/exact` requests. The columns for the `billing_events` table change in a migration (see [verify-event-system-database-scripts#48](https://github.com/alphagov/verify-event-system-database-scripts/pull/48)), adding a new `preferred_level_of_assurance` column. Required LOA information is now deprecated.
Changes in this PR:
* Record new `preferred_level_of_assurance` information.
* Do not record `required_level_of_assurance` (now deprecated).
The full set of changes being made is laid out in:
* [ADR 36 billing changes plan](https://docs.google.com/document/d/1hblVU0wquj6Z3-b9V75z6jb1wt3Nnpjh2MNHxNGgTBE/edit?usp=sharing)
For context, please see:
* [ADR …

ps34 Record new preferred LOA billing information

---

build/run-tests.sh
src/event_handler.py
test/event_handler_test.py

I've added the implicit lambda log group to terraform. This will need to be imported into the Terraform state manually. The log group is then subscribed to the CSLS Kinesis endpoint. This will send all event-recorder lambda output to Splunk.

Audit events to splunk
