- build.jenkins
> ABD-41: Split out building the docker image into its own stage.

- build.jenkins
Simple step added to satify requirement of having at least 1 step.
> ABD-41: The agent should belong to the stage, not the step.

- Dockerfile
- docker-entry.sh
- run-tests.sh
- test/event_handler_test.py
Authors: @andy-c-jones, @michaelwalker
> ABD-56: Use the latest verify-event-store-schema in integration tests

- .gitignore
- Dockerfile
- docker-entry.sh
- package.sh
- requirements/dev.txt
- requirements/prod.txt
- setup.sh
Authors: @andy-c-jones, @michaelwalker
> ABD-41: Added a package.sh script to package ready for lambda

- .pre-commit-config.yaml
- README.md
- pre-commit
This could do with improvements, but it's a start.
> BAU: added basic pre-commit.com config, script and instructions

- requirements/dev.txt
- test/event_handler_test.py
> BAU: Fixing flakey test by retrying the database connection

- test/decryption_test.py
- test/event_handler_test.py
- test/test_encrypter.py
> BAU: move padding logic into encryption function for clarity

- src/event_handler.py
- src/kms.py
- test/event_handler_test.py
Update an event recorder system to decrypt an encrypted event encryption key after fetching it from S3 bucket.
Authors: @adityapahuja
> 335: Add a step to decrypt an event encryption key

- src/event_handler.py
https://trello.com/c/CXREwQgE
boto3 decrypt returns bytes so use decode to return a password string.
> B&A: Decode DB Password from Environment Variable

- database-schema/V3__create_indexes_for_audit_billing_and_fraud_events_tables.sql
- test/event_handler_test.py
This pull requests contain 2 commits.
The first commit removes a duplicate variable from event_handler_test.py.
The second commit adds Event Id index to audit events table and adds Session Id index to billing and fraud events tables to help us to find the event quickly too.
Authors: @adityapahuja
> BAU: Remove a duplicate variable and add indexes to audit, billing and fraud tables

- README.md
- requirements/dev.txt
- src/event_mapper.py
- src/import_handler.py
- src/s3.py
- test/event_handler_test.py
- test/event_mapper_test.py
- test/import_handler_test.py
Add Lambda Handler (import_handler) to Import Records from an S3 bucket
Add Test for import_handler and modified event_mapper
Bump boto3 and moto library versions
Amend README.md to include instructions on replaying events
> EhIwDNNP: Get Missing Events Data into Event System from Hub Support

- src/event_handler.py
- Starter for 10 for some additional logging lines
- Might want some tests for these if we care about them
- Also worth dicussing the log level at which to log these things (I
went with all INFO so we always get all information)
> AUTO: Add more explicit logging

- src/event_handler.py
Reverts alphagov/verify-event-recorder-service#34
> Revert "AUTO: Add more explicit logging"

- src/event_handler.py
Set the logging level correctly in event_handler.py
> 3BI65oMG: Fix Event Recorder Logger - Correct Logging Level

- src/event_handler.py
- test/event_handler_test.py
Alter the exception handler to include additional info, including SQS message ID, event ID and and event type where available.
> 3BI65oMG: Fix Event Recorder Logger - Add extra error detail

- database-schema/V4__create_iam_user_permissions.sql
Added permission grants as new database-schema script.
> HSUj0wAP/214: Modify event reporter to use new IAM authentication to db

- database-schema/V4__create_iam_user_permissions.sql
- database-schema/V5__revoke_reader_user_permissions.sql
Add database script to `REVOKE` all permissions.
> zdOWAaBk: Clean up old db reader users and passwords

- docker-compose.yml
- postgres.Dockerfile
- test/event_handler_test.py
- test/import_handler_test.py
Ensure database created is called `events`
Include test-initialise-scripts in Postgres image
Update tests to use correct connection parameters
> rrGquzyO: Fix Recorder Service Test Failures

- .flake8
- Dockerfile
- build/lint.sh
- requirements/dev.txt
- src/database.py
- src/event_handler.py
- src/event_mapper.py
- src/import_handler.py
- src/kms.py
- src/s3.py
- test/event_handler_test.py
- test/event_mapper_test.py
- test/import_handler_test.py
- test/test_encrypter.py
Linting is still a manual step. This just makes it possible to do it. Then it goes and addresses everything the linter was complaining about.
The lint config has been taken from the reporter.
> BAU - Add flake8 linting

- src/database.py
- We no longer use it so we don't need to do this anymore.
> Do not populate the required loa column

- src/database.py
- Otherwise we will see the 'IndexError: list index out of range' error
> Fix this issues
